name: Continuous Intergation

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: playwright-self-hosted
  cancel-in-progress: false

jobs:
  test:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: [self-hosted, macOS, ARM64, docker, playwright]
    timeout-minutes: 30

    env:
      TEST_URL: https://www.saucedemo.com
      HEADLESS: "true"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Check Docker
        run: |
          docker --version
          docker compose version

      - name: Run Playwright Tests
        run: |
          docker compose up \
            --build \
            --abort-on-container-exit \
            --exit-code-from test

      - name: Stop Containers
        if: always()
        run: docker compose down --remove-orphans
